server:
  port: 9090

spring:
  application:
    name: demo-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/my_blog?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 2
      min-idle: 2
      max-active: 5
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      max-wait: 6000
      filter: slf4j

  rabbitmq:
    addresses: 121.43.181.100
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  boot:
    admin:
      client:
        url: http://127.0.0.1:9099
        instance:
          serviceHostType: IP


logging:
  level:
    com.fc.dao: debug


upload:
  uploadPath: D:\dev\files






# management 是所有actuator的配置
# management.endpoint.端点名.xxxx  对某个端点的具体配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    enabled-by-default: true  #默认开启所有监控端点  true
    health:
      show-details: ALWAYS




